title: Nyctibius
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://ersebreck.github.io/Nyctibius

aux_links: # remove if you don't want this link to appear on your pages
  Repository: https://github.com/Ersebreck/Nyctibius

logo: "./img/ny_logo.png"
title_only_logo: false
favicon_ico: "./img/ny_icon.ico"
